distro: trusty
language: go

go:
- 1.8

script:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get github.com/mitchellh/gox
- dep ensure -vendor-only
- gox -osarch="darwin/amd64 linux/amd64 linux/arm windows/amd64" -output="bin/ktail-{{.OS}}-{{.Arch}}"

deploy:
  provider: releases
  api_key:
    secure: $ENCRYPTED_GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
