distro: trusty
language: go

go:
- 1.8

script:
- curl https://glide.sh/get | sh
- go get github.com/mitchellh/gox
- glide install --strip-vendor
- gox -osarch="darwin/amd64 linux/amd64 linux/arm windows/amd64" -output="bin/ktail-{{.OS}}-{{.Arch}}"

deploy:
  provider: releases
  api_key:
    secure: "jX4ktRm+TCxCkO/tvMior3hNg8CXYihiwy3WAuEAJGyyfWwSHot+thZC8yTU50baoTyhlGXbWY0ZqTaSUq8+OWp/kY0bxcjV5a9zXt0tWPAp3wygLnNPyP9DXbdpAklNVZkH6f8GqZQa9VS9+KgJudD/LLrzL2+2xv4IBE/Nj47u/rnGWJocaf6+UQ7o9t9EV1xuY5AmiaTd/8Hif01hnuJZqOLgZVczSZZsIym47Vefa7MlC5+Wmkks5VBpjMf+h1HCJlCkKVCN/4X53AhqiZykGklbudqqLhrYr12vtecPtd0JmagsRZK8gEcjfeDBr9XUlDh3aG04icltuIhg3uO2KfmzPw+HUxd7EOOcSqJir9d5rZpxkcyVsgcylHOCRLwapeJw6JTdzbxUaTg9XBQsEs+n/GPexUF0G9vxkLG4bkBAyabCBS4O4rELrLh6QLiVsDziR9YH+NVQzb2YV4j7KLJiWAaD15NG6XWhdd/nU/AhA9anz0Gn58c9Yb7VFXc9/+xHbBDc81ctD2A+pLa/nqwKyW6PKk76mfAahvU8G29wopO2HH3qD7ertTKgUStoj0UL3XVhbsB7IO8oPMMQxi+wvCzOYyp40CG+PvXhkDBu48PLIwpSJDuTdMnShRFYZmkLsAHrBtK4kaGyaiwYfppW1ASlBw+9UmZyPfg="
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
