distro: trusty
language: go

go:
- "1.14.4"

env:
- GO111MODULE=on

script:
- env GO111MODULE=off go get github.com/mitchellh/gox
- go mod download
- gox -osarch="darwin/amd64 linux/amd64 linux/arm windows/amd64" -output="bin/ktail-{{.OS}}-{{.Arch}}"

deploy:
  provider: releases
  api_key:
    secure: "e9RO6eSSpqct33TiLGoT0VX6yQdv0R9DhxYf5OegsC5rueXF5zDx0kWkg1uCLVvmwa4H7Qq0p0YPlW3vyK5ZX0cjazAnD8zZ8kGg072SGWb/50PsD6aAePEiZmGuaMI7CX7PQwaJLHUEDmN00fwZJsYwKHJ5VlLjRWcmdVKr9L9RxbIhj8f2tKY78bNmG7FWTYqZ6yQQl2DbP+TrqBbMjxC2Qwt3mjFvwaJNSmCM573MFFyiCV8uNxjb82en1S46MiZMrZz1BXzSqRgWmOSdvfC8fvK4eJiIBrZSDwe3HFWl2lm52SlDoZ95b5iBbslcwBgNRUMxYZ1jOaJpWLrgxEPHe/1ueUa2WRw8D0xx7FByGK/uHUPnJQMDtXUDWtSpeaJbnmo6WqT1Jhf4dNHRqIrpjhwE7qVR9HvT4CX6RqpaSgCDlrRvkSZC3uEa2dWWafLTiNFqLDgp1oUwAgGSa9JGtuCjRhc4BwbmwQMfUg/fZOpW/GTZeWYm27cvlDd8XNCZfNuVU5KRIjecLCncRqorXNMVX7QbDPVkhkhI7JQ6iDo7PX6BtEUEtzgddz8k4rwzh8AY11jbLYT4X923PlYkVPx8/nCoHRmVuajUCjd8Jw5dB1pELtW9+denm/auNyp3pACxjC/n8j8GMNKdOPILlKdloh48AnWdJz9lsKI="
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
