#!/bin/sh

v=$(git tag -l | tail -n1)
if [ "$v" = "" ]; then
  echo "Cannot determine tag." >&2
  exit 1
fi

v=$(echo "$v" | sed -Ee 's#^v(.*)#\1#')

cat <<END >version.go
// Code generated by gen_version.sh, DO NOT EDIT.

package main

//go:generate sh -c ./gen_version.sh

const version = "$v"
END
