name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: {go-version: '^1.23'}
    - run: |
        go generate ./version.go
    - run: |
        env GO111MODULE=off go get github.com/mitchellh/gox
    - run: |
        gox -osarch="darwin/amd64 darwin/arm64 linux/amd64 linux/arm windows/amd64" -output="ktail-{{.OS}}-{{.Arch}}"
    - uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ktail-darwin-amd64
          ktail-darwin-arm64
          ktail-linux-amd64
          ktail-linux-arm
          ktail-windows-amd64.exe
